apiVersion: v1
kind: ServiceAccount
metadata:
  name: f1-backend
  labels:
    app.kubernetes.io/name: f1-backend
  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.clientId }}"
