namespace: f1-race-intelligence

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx
  host: f1.20.171.233.61.nip.io
  tls: false
